### ISSUE TITLE
16-bit version?

### ISSUE THREAD

**Issue by larsbrinkhoff** [aappleby/smhasher#47]
Hello,

Is it possible to create a version of MurmurHash where the result and intermediate values are 16 bits?

My intended application would be small, typically 8-bit, microcontrollers using small keysets.

**Comment by sebres** [comment]
Not about the possibility (which I think would be feasible)... 

But with 16 bits you can anyway not speak about "cryptographically strong" of the hash function, and there are few stricter (but faster and with the same distribution quality) algorithms available, that can be easier ported to 16-bit, for example the hashing algorithm of TCL-language or similar other...

Below you'll find for example one, I used for my IoT- resp. DIY-projects, that looks like:
<details>
Following example uses 32 bit hashing...

```c
#define __hash_len 32
typedef unsigned int __hash_int;

/* rotate left */
static inline __hash_int
_rol(register __hash_int x, register int n)
{
  return (x << n) | (x >> (__hash_len-n));
}
static inline __hash_int
_rol3(register __hash_int x)
{
  return (x << 3) | (x >> (__hash_len-3));
}

 /*
  * Tcl similar hashing algorithm, but instead simple left shift used ROL.
  * Additionally to the length of the hashed string, the seed can be mixed also.
  */
static inline __hash_int
_hash4strn(register __hash_int seed, register const char *string, register int len)
{
  register int l = len;
   
  while (len--) {
    seed += _rol3(seed) + *string++;
  }

  return seed ^ (__hash_int)l;
}
```
</details>
<br/>
Just redefine `__hash_len` to 16 and if expected on your platform just replace defenition of `__hash_int` from `unsigned int` with something you need, e. g. with `unsigned __int16`.

**Comment by larsbrinkhoff** [comment]
Thank you @sebres.  I'll take a look at your code.

I certainly don't need a cryptography-grade hash function.

**Comment by larsbrinkhoff** [comment]
Some variation of the TCL has looks fine.  Thanks.
