### ISSUE TITLE
Hash chain cycle length patterning of 32 bit murmur3 hash

### ISSUE THREAD

**Issue by colibrae** [aappleby/smhasher#54]
This is a very very simple test, but I have determined the maximum length one can start from a seed value, and hash the seed, then hash the hash of the seed, etc, and in a small sampling so far (about 25 runs) I have found that 3432278346 repetitions of this consistently produces a cycle. Occasionally it finds a cycle of 10, and one time out of 5 or so occurrances of 10 cycles I found a 9 cycle.

I am currently exploring the idea of a hashchain cycle search as a PoW algorithm, and I will be implementing a simple search that simply searches for the first hash in the chain repeating in the chain, and I'll get statistics for the cycle length frequency that shows different numbers. I'm not sure if this means the hash is weak, or anything, but I think the repetition patterns based on cryptographically random seeds is useful information. I will update once I have written the repetition cycle search and have some numbers for you.

**Comment by aappleby** [comment]
The number of cycles in a random permutation (which is what a 32-bit hash
of a 32-bit value is, assuming the operations in the hash are reversible)
is a well-studied statistics problem and probably won't result in any new
PoW methods.

https://en.wikipedia.org/wiki/Random_permutation_statistics#Expected_number_of_cycles_of_any_length_of_a_random_permutation

**Comment by colibrae** [comment]
That may well be the case for pure random numbers, but the clustering is not uniform, nor is a hashchain derived from a given nonce pure random. Here is an example run with 2^20 as the limit for the number of members of a hash chain examined (hashchains generated using murmur3 32 bit hashes:

```
2018/03/03 09:55:16 found repetition of 3252421861 iteration 1161
2018/03/03 09:55:16 Time to search 16.121611096s
2018/03/03 09:55:19 found repetition of 830256817 iteration 173
2018/03/03 09:55:19 Time to search 2.406310847s
2018/03/03 09:55:29 found repetition of 3295312596 iteration 747
2018/03/03 09:55:29 Time to search 10.354286078s
2018/03/03 09:55:47 found repetition of 3819752809 iteration 1294
2018/03/03 09:55:47 Time to search 17.92306673s
2018/03/03 09:55:50 found repetition of 231085138 iteration 203
2018/03/03 09:55:50 Time to search 2.809050958s
2018/03/03 09:55:50 found repetition of 3498695644 iteration 25
2018/03/03 09:55:50 Time to search 346.81367ms
2018/03/03 09:56:03 found repetition of 2193483119 iteration 913
2018/03/03 09:56:03 Time to search 12.665994442s
2018/03/03 09:56:29 found repetition of 579336984 iteration 1906
2018/03/03 09:56:29 Time to search 26.40701894s
```

**Comment by colibrae** [comment]
I should show the code that generates this:

```
func main() {
	for true {
		startTime := time.Now()
		for j := 0; j < maxIndices; j++ {
			nonce := hb.GetRandUint32()
			first := murmur3.Sum32(hb.Uint32ToBytes(nonce))
			subsequent := first
			for i := 1; i < maxIndices; i++ {
				subsequent = murmur3.Sum32(hb.Uint32ToBytes(subsequent))
				if subsequent == first {
					i = maxIndices
					fmt.Println("found repetition of", first, "iteration", j, "from nonce", nonce)
				}
			}
			if first == subsequent {
				j = maxIndices
			}
		}
		elapsedTime := time.Since(startTime)
		fmt.Println("Time to search", elapsedTime)
	}
}
```

**Comment by colibrae** [comment]
I wrote a test that tries out a fixed number of solutions per given length of chain, and let it run on progressive doubling chain lengths, and surprise surprise, it seems to be a direct linear relationship. That is, no matter the rise in the number of elements in the chain, the amount of solutions over time is proportional. Or in other words, longer chains don't mean a rise in difficulty, just less iterations to find a collision. So, as you explained, indeed this cannot be a proof of work, as it can't be adjusted.
