### ISSUE TITLE
studying the hashing algorithm.

### ISSUE THREAD

**Issue by ihsinme** [aappleby/smhasher#91]
good day.
sorry if my question is stupid.
As far as I understand, you are missing handling the `len = 0` situation.

https://github.com/aappleby/smhasher/blob/61a0530f28277f2e850bfc39600ce61d02b518de/src/MurmurHash1.cpp#L46

could you tell me why.

thanks

**Comment by sebres** [comment]
No, it is not missing.
This switch code handles the remaining bytes of the data (len < 4), which were not handled in cycle above (processing data in blocks with 4 bytes len). In case of 0 there are just no data anymore to be processed.
In case where len was initially 0 (no data at all), the result is simply depending on `seed` and magic constant `m` (0xc6a4a793).
